name: research
description: "Search the web and summarize findings on any topic"
trigger: "When the user asks to research something, look something up, or find information"
permissions:
  - http_request
entry_point: tool.py
author: builtin
trusted: true
created: "2026-02-27"
